### ISSUE TITLE
Finish implementing all Amalthea prometheus metrics

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/amalthea#156]
There are a few metrics left over to be implemented from https://github.com/SwissDataScienceCenter/amalthea/issues/143.

Implement all of them.

**Comment by Panaetius** [comment]
Check if we can get this in grafana/by quering prometheus directly

**Comment by olevski** [comment]
We need to fix the already implemented metrics from Amalthea. The reason for this is that we have several metrics of the gauge type (which can increase or decrease) in value. These metrics are made to reflect the current state of the sessions (i.e. how many are currently in a failed or running or starting state). These metrics work perfectly when they start recording when there are no servers in the cluster. But if the metrics are introduced when there already is some active sessions in the cluster then some gagues will inevitably show negative or non-sensical values.

For example if the cluster had 10 sessions in a running state when the metrics were first introduced and these are all shutdown quickly after that the value of the `sessions_running` gauge metric will go to -10. Then when 10 new sessions are launched the following day the value of this metric will go to 0.

It is also unacceptable IMO to require an amalthea deployment to shut down all its sessions just so the metrics are working   correctly.
