### ISSUE TITLE
Use http k8s probes for Jupyter servers

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/amalthea#71]
As wisely suggested by @ableuler , the following should probably work and avoid some of the problems we have had trying to use http probes in the past:

>  I thought about this a bit, and I think the following should work and would be ok from a security standpoint:
> - back to http probe hitting :8888
> - make jupyter server listen on all interfaces (0.0.0.0)
> - use an ingress network policy to block all traffic into the pod which tries to hit :8888 (note that the probes ARE in fact  exempt from those policies)
> - always use the oidc proxy, even for non-oidc sessions - and just whitelist all ips for non-oidc sessions

**Comment by ableuler** [comment]
Considering that my last two attempts of adding a reliable probe for the jupyter container have failed gloriously, I'd wait a bit before adding the `wise` label to this suggestion 😄 - but thanks!

**Comment by ableuler** [comment]
Closed in https://github.com/SwissDataScienceCenter/amalthea/pull/80
